I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 30, in script
    e "Once you add a story, pictures, and music, you can release it to the world!"
Exception: Sayer 'e' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 30, in script
    e "Once you add a story, pictures, and music, you can release it to the world!"
  File "C:\Users\tksth\Desktop\renpy-8.1.0-sdk\renpy\ast.py", line 890, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\tksth\Desktop\renpy-8.1.0-sdk\renpy\ast.py", line 783, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'e' is not defined.

Windows-10-10.0.19045 AMD64
Ren'Py 8.1.0.23051307
해방 1.0
Thu May 25 21:54:21 2023
