I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 278, in script
    with black
  File "game/script.rpy", line 278, in <module>
    with black
NameError: name 'black' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 278, in script
    with black
  File "C:\Users\tksth\Desktop\renpy-8.1.0-sdk\renpy\ast.py", line 1671, in execute
    trans = renpy.python.py_eval(self.expr)
  File "C:\Users\tksth\Desktop\renpy-8.1.0-sdk\renpy\python.py", line 1153, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\tksth\Desktop\renpy-8.1.0-sdk\renpy\python.py", line 1146, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 278, in <module>
    with black
NameError: name 'black' is not defined

Windows-10-10.0.19045 AMD64
Ren'Py 8.1.0.23051307
해방 1.0
Sun Jun  4 21:34:45 2023
